services:
  ai_service:
    build: ./ai_service
    ports:
      - "8000:8000"
    networks:
      - app-network

  feed_service:
    build: ./feed_service
    ports:
      - "8001:8001"
    volumes:
      - ./images:/images
      - shared-data:/shared
    depends_on:
      - ai_service
    networks:
      - app-network

  dashboard_service:
    build: ./dashboard_service
    ports:
      - "8002:8002"
    depends_on:
      - feed_service
    networks:
      - app-network

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge

